const axios = require('axios'); // import axios
const https = require('https');

const httpsAgent = new https.Agent({
  rejectUnauthorized: false // Bypass SSL verification
});

// first make sure you have set permision in proxmox (use video)
// Use the ticket and CSRF token obtained from the API (use video)
// this ticket  generated by the responde using postman, this also  might expire at some point (use video)
const ticket = 'PVE:API@pve:661DDE41::IrBy/rJChdD4n72FImaYLaXxMBAypdkYYEf3YjI7o4NaXdEQHhfBZcdwJ8aYTjCi+TH6/RHrhkMJqCteAO7NYfYFhISdwVE2sALDaW6s6slVGvdrskBs/gdXqmBXaogreBgKhPYC2JpXv5IwQH/9csIbtyB6IVe+2+hAFCVBBkrdzJ/XQwG/Xye88MvQsCCkobOBYBYa4w7LmTbIt5/UiLkV1niskQnPyRh8jWrMy5SWCUcoNHtXdZDeNV4tiPyKUkhHOjtKagHM4zbK/hQ9XYKN6CQSt0qqQWljOr5Cc8K9v+EVVJMpenjFtkM4pFZRxQ6OXYwAt0GmBM+lC0B9/A=='; // Replace with the full ticket from the response
const csrfToken = '661DDE41:choByLw2vnRzxEIn7Y9PQ6w7fY5QzxclXtcU0VaH1Mk'; // Replace with the CSRF token from the response using postman (use the video)

const host = 'https://192.168.0.79:8006'; // Your Proxmox server address
const nodeId = 'pve'; // Node name where the VM is hosted
const vmId = 100; // VM ID that you want to start

// Set up the cookie in the header to use the ticket
const cookie = `PVEAuthCookie=${encodeURIComponent(ticket)}`; // this thing is so stupid, encode the ticket 

// endpoint to start vm in proxmox, reference the resource tree on proxmox documentation to create more endpoint such as stop, current, reboot, reset, resume, shutdown....
axios.post(`${host}/api2/json/nodes/${nodeId}/qemu/${vmId}/status/start`, {}, {
  headers: {
    'Cookie': cookie,
    'CSRFPreventionToken': csrfToken
  },
  httpsAgent
})
.then(response => {
  console.log('VM started successfully:', response.data);
})
.catch(error => {
  console.error('Error starting VM:', error);
});
